// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJs6nsP8ZpcpCksC2dFsXsK2SLxTV14Y',
    appId: '1:223646686241:web:bef19b208f9f1b54a45760',
    messagingSenderId: '223646686241',
    projectId: 'avatar-ai-e7c65',
    authDomain: 'avatar-ai-e7c65.firebaseapp.com',
    storageBucket: 'avatar-ai-e7c65.firebasestorage.app',
    measurementId: 'G-V5SMF5GWKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa16DBaDupRe6st8Io-Z8xUl3RNZmhTPQ',
    appId: '1:223646686241:android:b50691825a610cdfa45760',
    messagingSenderId: '223646686241',
    projectId: 'avatar-ai-e7c65',
    storageBucket: 'avatar-ai-e7c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMLCy7NiCFGLVQi2HU4dcLhzj5WpatH5M',
    appId: '1:223646686241:ios:3a9de11d8305d9c2a45760',
    messagingSenderId: '223646686241',
    projectId: 'avatar-ai-e7c65',
    storageBucket: 'avatar-ai-e7c65.firebasestorage.app',
    iosBundleId: 'com.example.avatarAi',
  );
}
